In [1]:
import torch
import numpy as np

In [3]:
data = np.random.rand(5,5)

In [4]:
data

array([[0.65037125, 0.89320726, 0.37411988, 0.96139761, 0.72818957],
       [0.86394478, 0.71476898, 0.42235692, 0.68894415, 0.53481756],
       [0.46912596, 0.6568247 , 0.06532341, 0.32014235, 0.55484491],
       [0.65136039, 0.8353833 , 0.57131409, 0.39866451, 0.90393251],
       [0.3632311 , 0.68197682, 0.53499599, 0.00441823, 0.78549969]])

In [5]:
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[0.6504, 0.8932, 0.3741, 0.9614, 0.7282],
        [0.8639, 0.7148, 0.4224, 0.6889, 0.5348],
        [0.4691, 0.6568, 0.0653, 0.3201, 0.5548],
        [0.6514, 0.8354, 0.5713, 0.3987, 0.9039],
        [0.3632, 0.6820, 0.5350, 0.0044, 0.7855]], dtype=torch.float64)

In [7]:
x_np = torch.from_numpy(data)

In [8]:
x_np

tensor([[0.6504, 0.8932, 0.3741, 0.9614, 0.7282],
        [0.8639, 0.7148, 0.4224, 0.6889, 0.5348],
        [0.4691, 0.6568, 0.0653, 0.3201, 0.5548],
        [0.6514, 0.8354, 0.5713, 0.3987, 0.9039],
        [0.3632, 0.6820, 0.5350, 0.0044, 0.7855]], dtype=torch.float64)

In [10]:
x_ones = torch.ones_like(x_data)

In [11]:
x_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [12]:
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [13]:
x_rand

tensor([[0.1142, 0.9232, 0.3299, 0.0584, 0.0336],
        [0.3326, 0.9671, 0.1567, 0.3895, 0.4031],
        [0.0193, 0.7873, 0.2553, 0.4651, 0.6138],
        [0.2338, 0.9324, 0.3030, 0.2105, 0.7594],
        [0.8126, 0.5312, 0.8182, 0.7119, 0.5041]])

In [14]:
x_zero = torch.zeros_like(x_data)

In [15]:
x_zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [18]:
shape = (2,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [19]:
rand_tensor

tensor([[0.5095, 0.0157],
        [0.0078, 0.8525]])

In [20]:
ones_tensor

tensor([[1., 1.],
        [1., 1.]])

In [21]:
zeros_tensor

tensor([[0., 0.],
        [0., 0.]])

In [29]:
rand_tensor = torch.rand((3,3))

In [30]:
rand_tensor.shape

torch.Size([3, 3])

In [31]:
rand_tensor.dtype

torch.float32

In [32]:
rand_tensor.device

device(type='cpu')

In [33]:
torch.cuda.is_available()

False

In [34]:
ones_tensor = torch.ones(4, 4)

In [35]:
ones_tensor[0]

tensor([1., 1., 1., 1.])

In [36]:
ones_tensor[:, 0]

tensor([1., 1., 1., 1.])

In [37]:
rand_tensor

tensor([[0.9112, 0.3107, 0.9816],
        [0.2061, 0.5889, 0.3835],
        [0.7796, 0.2611, 0.0423]])

In [38]:
rand_tensor[0]

tensor([0.9112, 0.3107, 0.9816])

In [39]:
rand_tensor[:, 0]

tensor([0.9112, 0.2061, 0.7796])

In [40]:
rand_tensor[:, -1]

tensor([0.9816, 0.3835, 0.0423])

In [41]:
rand_tensor[:,1] = 0

In [42]:
rand_tensor

tensor([[0.9112, 0.0000, 0.9816],
        [0.2061, 0.0000, 0.3835],
        [0.7796, 0.0000, 0.0423]])

In [47]:
rand_tensor[:,1] = np.random.rand()

In [48]:
rand_tensor

tensor([[0.9112, 0.3383, 0.9816],
        [0.2061, 0.3383, 0.3835],
        [0.7796, 0.3383, 0.0423]])

In [51]:
ones_tensor = torch.ones((3,3))

In [52]:
cat_tensor = torch.cat([rand_tensor, ones_tensor], dim=1)

In [53]:
cat_tensor

tensor([[0.9112, 0.3383, 0.9816, 1.0000, 1.0000, 1.0000],
        [0.2061, 0.3383, 0.3835, 1.0000, 1.0000, 1.0000],
        [0.7796, 0.3383, 0.0423, 1.0000, 1.0000, 1.0000]])

In [54]:
cat_tensor = torch.cat([rand_tensor, ones_tensor], dim=0)

In [55]:
cat_tensor

tensor([[0.9112, 0.3383, 0.9816],
        [0.2061, 0.3383, 0.3835],
        [0.7796, 0.3383, 0.0423],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [56]:
cat_tensor.T

tensor([[0.9112, 0.2061, 0.7796, 1.0000, 1.0000, 1.0000],
        [0.3383, 0.3383, 0.3383, 1.0000, 1.0000, 1.0000],
        [0.9816, 0.3835, 0.0423, 1.0000, 1.0000, 1.0000]])

In [57]:
cat_tensor_mult = cat_tensor @ cat_tensor.T

In [58]:
cat_tensor_mult

tensor([[1.9082, 0.6787, 0.8663, 2.2311, 2.2311, 2.2311],
        [0.6787, 0.3040, 0.2913, 0.9279, 0.9279, 0.9279],
        [0.8663, 0.2913, 0.7240, 1.1602, 1.1602, 1.1602],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000]])

In [60]:
cat_tensor.matmul(cat_tensor.T)

tensor([[1.9082, 0.6787, 0.8663, 2.2311, 2.2311, 2.2311],
        [0.6787, 0.3040, 0.2913, 0.9279, 0.9279, 0.9279],
        [0.8663, 0.2913, 0.7240, 1.1602, 1.1602, 1.1602],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000],
        [2.2311, 0.9279, 1.1602, 3.0000, 3.0000, 3.0000]])

In [61]:
new_cat_tensor = torch.rand(cat_tensor_mult.shape)

In [64]:
cat_tensor * torch.ones(cat_tensor.shape)

tensor([[0.9112, 0.3383, 0.9816],
        [0.2061, 0.3383, 0.3835],
        [0.7796, 0.3383, 0.0423],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [65]:
cat_tensor

tensor([[0.9112, 0.3383, 0.9816],
        [0.2061, 0.3383, 0.3835],
        [0.7796, 0.3383, 0.0423],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [66]:
agg = rand_tensor.sum()

In [67]:
agg

tensor(4.3192)

In [68]:
agg_item = agg.item()

In [69]:
agg_item

4.319199085235596

In [73]:
torch.ones((3,3)).multiply(5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [74]:
torch.ones((3,3)).add_(5)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [75]:
ones_np = ones_tensor.numpy()

In [76]:
ones_np

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [77]:
ones_tensor.mul_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [78]:
ones_np

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [80]:
n_array = np.ones((5, 3))

In [81]:
ones_tensor = torch.from_numpy(n_array)

In [82]:
ones_tensor.add_(3)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)

In [83]:
n_array

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [86]:
arr = np.arange(1, 10, 1)

In [87]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr_tensor = torch.tensor(arr)

In [89]:
arr_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [90]:
arr_tensor.add_(4)

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=torch.int32)

In [91]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
random_tensor = torch.rand((5, 3))

In [93]:
random_tensor

tensor([[0.2834, 0.0378, 0.3493],
        [0.2774, 0.3243, 0.2011],
        [0.3076, 0.7487, 0.6890],
        [0.6944, 0.7458, 0.1496],
        [0.2153, 0.5109, 0.0054]])

In [95]:
random_tensor @ random_tensor.T

tensor([[0.2038, 0.1611, 0.3561, 0.2773, 0.0822],
        [0.1611, 0.2226, 0.4667, 0.4646, 0.2265],
        [0.3561, 0.4667, 1.1298, 0.8750, 0.4525],
        [0.2773, 0.4646, 0.8750, 1.0608, 0.5314],
        [0.0822, 0.2265, 0.4525, 0.5314, 0.3074]])

In [97]:
random_tensor * random_tensor

tensor([[8.0344e-02, 1.4288e-03, 1.2200e-01],
        [7.6974e-02, 1.0515e-01, 4.0445e-02],
        [9.4619e-02, 5.6052e-01, 4.7469e-01],
        [4.8220e-01, 5.5628e-01, 2.2373e-02],
        [4.6346e-02, 2.6105e-01, 2.9291e-05]])

In [99]:
n_cat_tensor = torch.cat([random_tensor * random_tensor, random_tensor * random_tensor], dim = 0)

In [100]:
n_cat_tensor

tensor([[8.0344e-02, 1.4288e-03, 1.2200e-01],
        [7.6974e-02, 1.0515e-01, 4.0445e-02],
        [9.4619e-02, 5.6052e-01, 4.7469e-01],
        [4.8220e-01, 5.5628e-01, 2.2373e-02],
        [4.6346e-02, 2.6105e-01, 2.9291e-05],
        [8.0344e-02, 1.4288e-03, 1.2200e-01],
        [7.6974e-02, 1.0515e-01, 4.0445e-02],
        [9.4619e-02, 5.6052e-01, 4.7469e-01],
        [4.8220e-01, 5.5628e-01, 2.2373e-02],
        [4.6346e-02, 2.6105e-01, 2.9291e-05]])

In [101]:
n_cat_tensor = torch.cat([random_tensor * random_tensor, random_tensor * random_tensor], dim = 1)